In [29]:
import pandas as pd
import numpy as np

jahr = '2025'

if jahr == '2025':
    ghp="Daten entsoe/Gro_handelspreise_202501010000_202601010000_Stunde.csv"
    psf="Daten entsoe/Physikalischer_Stromfluss_202501010000_202601010000_Viertelstunde.csv"
    rez='Daten entsoe/Realisierte_Erzeugung_202501010000_202601010000_Viertelstunde.csv'
else:
    ghp="Daten entsoe/Gro_handelspreise_202311010000_202502010000_Stunde.csv"
    psf="Daten entsoe/Physikalischer_Stromfluss_202311010000_202502010000_Viertelstunde.csv"
    rez='Daten entsoe/Realisierte_Erzeugung_202311010000_202502010000_Viertelstunde.csv'

Strompreis=pd.read_csv(ghp,na_values='-',header=0 ,sep=';', decimal=",", thousands=".")

In [30]:
Strompreis['Datum']=pd.to_datetime(Strompreis['Datum von'],format='%d.%m.%Y %H:%M')
Strompreis=Strompreis.sort_values('Datum',kind='stable')
Strompreis['Datum']=pd.to_datetime(Strompreis['Datum von'],format='%d.%m.%Y %H:%M')
Strompreis['Datum']=Strompreis['Datum'].dt.tz_localize('Europe/Berlin',ambiguous='infer')
Strompreis['Date']=Strompreis['Datum'].dt.tz_convert('UTC')
Strompreis=Strompreis.set_index('Date')

In [31]:
datei=psf
dtype={'Datum von':"string",'Datum bis':"string"
       ,'Nettoexport [MWh] Originalauflösungen':np.float64
       ,'Niederlande (Export) [MWh] Originalauflösungen':np.float64
       ,'Niederlande (Import) [MWh] Originalauflösungen':np.float64
       ,'Schweiz (Export) [MWh] Originalauflösungen':np.float64
       ,'Schweiz (Import) [MWh] Originalauflösungen':np.float64
       ,'Dänemark (Export) [MWh] Originalauflösungen':np.float64
       ,'Dänemark (Import) [MWh] Originalauflösungen':np.float64
       ,'Tschechien (Export) [MWh] Originalauflösungen':np.float64
       ,'Tschechien (Import) [MWh] Originalauflösungen':np.float64
       ,'Luxemburg (Export) [MWh] Originalauflösungen':np.float64
       ,'Luxemburg (Import) [MWh] Originalauflösungen':np.float64
       ,'Schweden (Export) [MWh] Originalauflösungen':np.float64
       ,'Schweden (Import) [MWh] Originalauflösungen':np.float64
       ,'Österreich (Export) [MWh] Originalauflösungen':np.float64
       ,'Österreich (Import) [MWh] Originalauflösungen':np.float64
       ,'Frankreich (Export) [MWh] Originalauflösungen':np.float64
       ,'Frankreich (Import) [MWh] Originalauflösungen':np.float64
       ,'Polen (Export) [MWh] Originalauflösungen':np.float64
       ,'Polen (Import) [MWh] Originalauflösungen':np.float64
       ,'Norwegen (Export) [MWh] Originalauflösungen':np.float64
       ,'Norwegen (Import) [MWh] Originalauflösungen':np.float64
       ,'Belgien (Export) [MWh] Originalauflösungen':np.float64
       ,'Belgien (Import) [MWh] Originalauflösungen':np.float64}


#Stromfluss=pd.read_csv("Daten entsoe/Physikalischer_Stromfluss_202311010000_202502010000_Viertelstunde.csv",sep=';', decimal=",", thousands=".",dtype=dtype,on_bad_lines='skip')
Stromfluss=pd.read_csv(datei,sep=';', decimal=",", thousands=".",header=0,na_values='-',on_bad_lines='skip')

In [32]:
Stromfluss['Datum']=pd.to_datetime(Stromfluss['Datum von'],format='%d.%m.%Y %H:%M')
#Stromfluss=Stromfluss.sort_values('Datum',kind='stable')
Stromfluss['Datum']=pd.to_datetime(Stromfluss['Datum von'],format='%d.%m.%Y %H:%M')
Stromfluss['Datum']=Stromfluss['Datum'].dt.tz_localize('Europe/Berlin',ambiguous='infer')
Stromfluss['Date']=Stromfluss['Datum'].dt.tz_convert('UTC')
Stromfluss=Stromfluss[Stromfluss['Date'].dt.year==int(jahr)]
Stromfluss=Stromfluss.set_index('Date').fillna(0)
pm_cat=Stromfluss['Nettoexport [MWh] Originalauflösungen']
Stromfluss['+-']=(np.where(pm_cat<0,'0: Import','1: Export'))
Strompreis=Strompreis.reindex(Stromfluss.index).ffill()
#Stromfluss.rename(columns={'Nettoexport [MWh] Originalauflösungen':'Nettoexport [TWh]'})
Stromfluss['Preis']=Strompreis['Deutschland/Luxemburg [€/MWh] Originalauflösungen']
Stromfluss['Nettoexport [TWh]']=Stromfluss['Nettoexport [MWh] Originalauflösungen']/1000000
Stromfluss['Wert Mio €']=Stromfluss['Preis']*Stromfluss['Nettoexport [MWh] Originalauflösungen']/1000000
#Stromfluss=Stromfluss.set_index('Date')

In [33]:
# funktioniert: 
#Stromfluss.groupby([Stromfluss.index.month,Stromfluss['+-']])[['Nettoexport [TWh]','Wert Mio €']].agg(['sum'])
df=Stromfluss.reset_index()
df['Monat']=df['Date'].dt.month
df['Jahr']=df['Date'].dt.year
Strom=pd.pivot_table(df,index='Monat', columns=['+-'],values=['Wert Mio €','Nettoexport [TWh]'], aggfunc='sum',margins=True,margins_name=jahr)

In [34]:
#Strom['Durchschnittspreis [€/MWh]','0: Import']=Strom['Wert Mio €']['0: Import']/Strom['Nettoexport [TWh]']['0: Import']
#Strom['Durchschnittspreis [€/MWh]','1: Export']=Strom['Wert Mio €']['1: Export']/Strom['Nettoexport [TWh]']['1: Export']
Strom=Strom.join(Strom[['Wert Mio €']].div(Strom['Nettoexport [TWh]']).rename(columns={'Wert Mio €':'Durchschnittspreis [€/MWh]'}))
Strom=Strom.drop(columns=('Durchschnittspreis [€/MWh]',jahr), axis=1)

In [35]:
Strom

      Nettoexport [TWh]                      Wert Mio €              \
+-            0: Import 1: Export      2025   0: Import   1: Export
Monat
1             -2.242705  1.583959 -0.658747 -362.696735  101.743861
2             -1.232080  0.658022 -0.574058 -190.657563   74.820721
3                   NaN  0.000000  0.000000         NaN    0.000000
4                   NaN  0.000000  0.000000         NaN    0.000000
5                   NaN  0.000000  0.000000         NaN    0.000000
6                   NaN  0.000000  0.000000         NaN    0.000000
7                   NaN  0.000000  0.000000         NaN    0.000000
8                   NaN  0.000000  0.000000         NaN    0.000000
9                   NaN  0.000000  0.000000         NaN    0.000000
10                  NaN  0.000000  0.000000         NaN    0.000000
11                  NaN  0.000000  0.000000         NaN    0.000000
12                  NaN  0.000000  0.000000         NaN    0.000000
2025          -3.474785  2.241980 -1.232805 -553.354298  176.564582

                  Durchschnittspreis [€/MWh]
+-           2025                  0: Import   1: Export
Monat
1     -260.952874                 161.722873   64.233918
2     -115.836842                 154.744467  113.705544
3        0.000000                        NaN         NaN
4        0.000000                        NaN         NaN
5        0.000000                        NaN         NaN
6        0.000000                        NaN         NaN
7        0.000000                        NaN         NaN
8        0.000000                        NaN         NaN
9        0.000000                        NaN         NaN
10       0.000000                        NaN         NaN
11       0.000000                        NaN         NaN
12       0.000000                        NaN         NaN
2025  -376.789716                 159.248488   78.753853

In [36]:
datei=rez
Stromerzeugung=pd.read_csv(datei,sep=';', decimal=",", thousands=".",header=0,na_values='-',on_bad_lines='skip')

In [37]:
Stromerzeugung['Datum']=pd.to_datetime(Stromerzeugung['Datum von'],format='%d.%m.%Y %H:%M')
Stromerzeugung['Datum']=Stromerzeugung['Datum'].dt.tz_localize('Europe/Berlin',ambiguous='infer')
Stromerzeugung['Date']=Stromerzeugung['Datum'].dt.tz_convert('UTC')
Stromerzeugung=Stromerzeugung[Stromerzeugung['Date'].dt.year==int(jahr)]
Stromerzeugung=Stromerzeugung.set_index('Date').fillna(0)

In [38]:
replace={ 
'Biomasse [MWh] Originalauflösungen':'Biomasse'
,'Wasserkraft [MWh] Originalauflösungen':'Wasserkraft'
,'Wind Offshore [MWh] Originalauflösungen':'Wind off'
,'Wind Onshore [MWh] Originalauflösungen':'Wind on'
,'Photovoltaik [MWh] Originalauflösungen':'Photovoltaik'
,'Sonstige Erneuerbare [MWh] Originalauflösungen':'Sonstige Erneuerbare'
,'Kernenergie [MWh] Originalauflösungen':'Kernenergie'
,'Braunkohle [MWh] Originalauflösungen':'Braunkohle'
,'Steinkohle [MWh] Originalauflösungen':'Steinkohle'
,'Erdgas [MWh] Originalauflösungen':'Erdgas'
,'Pumpspeicher [MWh] Originalauflösungen':'Pumpspeicher'
,'Sonstige Konventionelle [MWh] Originalauflösungen':'Sonstige Konventionelle'}
Stromerzeugung=Stromerzeugung.rename(columns=replace)
Stromerzeugung['Preis']=Strompreis['Deutschland/Luxemburg [€/MWh] Originalauflösungen']

In [39]:
piv=[]
for cur in replace:
    sm=replace[cur]
    Stromerzeugung[sm+' Wert Mio €']=Stromerzeugung['Preis']*Stromerzeugung[sm]/1000000
    Stromerzeugung[sm]=Stromerzeugung[sm]/1000000
    piv=piv+[sm,sm+' Wert Mio €']
Stromerzeugung['+-']=(np.where(Stromerzeugung['Preis']<0,'0: neg','1: pos'))

In [40]:
df=Stromerzeugung.reset_index()
df['Monat']=df['Date'].dt.month
df['Jahr']=df['Date'].dt.year
#df=df.drop(columns=['Date','Datum von','Datum bis','Jahr','Datum','Preis'], axis=1)
df_mon=df.groupby(['Monat','+-']).sum(numeric_only=True)
df_jahr  =df.groupby(['Jahr','+-']).sum(numeric_only=True).rename_axis(index={'Jahr':'Monat'})

df_mon=df_mon.drop(columns=('Jahr'), axis=1)
df_jahr=df_jahr.drop(columns=('Monat'), axis=1)

df_erg=pd.concat([df_mon,df_jahr])

for cur in replace:
    sm=replace[cur]
    df_erg[sm+' €/MWh']=df_erg[sm+' Wert Mio €']/df_erg[sm]


#Strom_ez=pd.pivot_table(df,index='Monat', columns=['+-'],values=piv, aggfunc='sum',margins=True,margins_name=jahr)
#Strom_ez=Strom_ez.join(Strom[['Wert Mio €']].div(Strom['Nettoexport [TWh]']).rename(columns={'Wert Mio €':'Durchschnittspreis [€/MWh]'}))
#Strom_ez=Strom_ez.drop(columns=('Durchschnittspreis [€/MWh]',jahr), axis=1)

In [41]:
df_erg.to_csv('test.csv')

In [42]:
df_erg

              Biomasse  Wasserkraft  Wind off    Wind on  Photovoltaik  \
Monat +-
1     0: neg  0.054821     0.017539  0.032575   0.515905      0.061542
      1: pos  3.147844     1.119844  2.506613  12.484586      1.627996
2     1: pos  1.379227     0.471449  1.164841   3.431751      1.176342
3     1: pos  0.000000     0.000000  0.000000   0.000000      0.000000
4     1: pos  0.000000     0.000000  0.000000   0.000000      0.000000
5     1: pos  0.000000     0.000000  0.000000   0.000000      0.000000
6     1: pos  0.000000     0.000000  0.000000   0.000000      0.000000
7     1: pos  0.000000     0.000000  0.000000   0.000000      0.000000
8     1: pos  0.000000     0.000000  0.000000   0.000000      0.000000
9     1: pos  0.000000     0.000000  0.000000   0.000000      0.000000
10    1: pos  0.000000     0.000000  0.000000   0.000000      0.000000
11    1: pos  0.000000     0.000000  0.000000   0.000000      0.000000
12    1: pos  0.000000     0.000000  0.000000   0.000000      0.000000
2025  0: neg  0.054821     0.017539  0.032575   0.515905      0.061542
      1: pos  4.527071     1.591293  3.671454  15.916337      2.804337

              Sonstige Erneuerbare  Kernenergie  Braunkohle  Steinkohle  \
Monat +-
1     0: neg              0.001462          0.0    0.045756    0.028566
      1: pos              0.078934          0.0    6.789585    3.586727
2     1: pos              0.033796          0.0    3.395026    2.159997
3     1: pos              0.000000          0.0    0.000000    0.000000
4     1: pos              0.000000          0.0    0.000000    0.000000
5     1: pos              0.000000          0.0    0.000000    0.000000
6     1: pos              0.000000          0.0    0.000000    0.000000
7     1: pos              0.000000          0.0    0.000000    0.000000
8     1: pos              0.000000          0.0    0.000000    0.000000
9     1: pos              0.000000          0.0    0.000000    0.000000
10    1: pos              0.000000          0.0    0.000000    0.000000
11    1: pos              0.000000          0.0    0.000000    0.000000
12    1: pos              0.000000          0.0    0.000000    0.000000
2025  0: neg              0.001462          0.0    0.045756    0.028566
      1: pos              0.112730          0.0   10.184611    5.746724

                 Erdgas  ...  Wind off €/MWh  Wind on €/MWh  \
Monat +-                 ...
1     0: neg   0.056281  ...       -0.138839      -0.113442
      1: pos   7.880320  ...      105.408445      90.357486
2     1: pos   3.901577  ...      134.431819     128.307152
3     1: pos   0.000000  ...             NaN            NaN
4     1: pos   0.000000  ...             NaN            NaN
5     1: pos   0.000000  ...             NaN            NaN
6     1: pos   0.000000  ...             NaN            NaN
7     1: pos   0.000000  ...             NaN            NaN
8     1: pos   0.000000  ...             NaN            NaN
9     1: pos   0.000000  ...             NaN            NaN
10    1: pos   0.000000  ...             NaN            NaN
11    1: pos   0.000000  ...             NaN            NaN
12    1: pos   0.000000  ...             NaN            NaN
2025  0: neg   0.056281  ...       -0.138839      -0.113442
      1: pos  11.781897  ...      114.616682      98.539885

              Photovoltaik €/MWh  Sonstige Erneuerbare €/MWh  \
Monat +-
1     0: neg           -0.183403                   -0.110547
      1: pos          119.617312                  118.665989
2     1: pos          120.923231                  138.864196
3     1: pos                 NaN                         NaN
4     1: pos                 NaN                         NaN
5     1: pos                 NaN                         NaN
6     1: pos                 NaN                         NaN
7     1: pos                 NaN                         NaN
8     1: pos                 NaN                         NaN
9     1: pos                 NaN                         NaN
10    1: pos                 NaN                         NaN
11    1: pos                 NaN                         NaN
12    1: pos                 NaN                         NaN
2025  0: neg           -0.183403                   -0.110547
      1: pos          120.165109                  124.721389

              Kernenergie €/MWh  Braunkohle €/MWh  Steinkohle €/MWh  \
Monat +-
1     0: neg                NaN         -0.110343         -0.102286
      1: pos                NaN        127.494047        129.252891
2     1: pos                NaN        139.694916        139.754343
3     1: pos                NaN               NaN               NaN
4     1: pos                NaN               NaN               NaN
5     1: pos                NaN               NaN               NaN
6     1: pos                NaN               NaN               NaN
7     1: pos                NaN               NaN               NaN
8     1: pos                NaN               NaN               NaN
9     1: pos                NaN               NaN               NaN
10    1: pos                NaN               NaN               NaN
11    1: pos                NaN               NaN               NaN
12    1: pos                NaN               NaN               NaN
2025  0: neg                NaN         -0.110343         -0.102286
      1: pos                NaN        131.561190        133.200028

              Erdgas €/MWh  Pumpspeicher €/MWh  Sonstige Konventionelle €/MWh
Monat +-
1     0: neg     -0.103112           -0.102187                      -0.109725
      1: pos    134.418009          161.487537                     118.887207
2     1: pos    143.610935          169.241553                     138.984223
3     1: pos           NaN                 NaN                            NaN
4     1: pos           NaN                 NaN                            NaN
5     1: pos           NaN                 NaN                            NaN
6     1: pos           NaN                 NaN                            NaN
7     1: pos           NaN                 NaN                            NaN
8     1: pos           NaN                 NaN                            NaN
9     1: pos           NaN                 NaN                            NaN
10    1: pos           NaN                 NaN                            NaN
11    1: pos           NaN                 NaN                            NaN
12    1: pos           NaN                 NaN                            NaN
2025  0: neg     -0.103112           -0.102187                      -0.109725
      1: pos    137.462248          163.705705                     124.718236

[15 rows x 37 columns]